dist: xenial

language: python

python:
- '3.6'

install:
- python setup.py install

before_script:
- pip install --upgrade pip
- pip install codecov
- pip install coveralls
- pip install matplotlib
- pip install nose-timer

script:
  # Notes on nose:
  # Travis CI pre-installs `nose`
  # https://github.com/coagulant/coveralls-python#nosetests
  # http://nose.readthedocs.org/en/latest/plugins/skip.html
- nosetests --no-skip --with-coverage --cover-package=runesdb --with-doctest --with-timer

after_success:
- codecov
